name: Deploy to Cocoapods

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Cocoapods # https://cocoapods.org/pods/KHTweetNacl
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create and Push Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -eo pipefail
          VERSION=$(grep -oE 's.version.*= *"[^"]*"' *.podspec | grep -oE '"[^""]*"' | tr -d '"')
          echo "Detected version: $VERSION"
          git tag $VERSION
          git push origin $VERSION

      - name: Deploy to Cocoapods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          set -eo pipefail
          pod lib lint --allow-warnings
          pod trunk push --allow-warnings
